modLoader = "javafml" #mandatory
loaderVersion = "[36,)" #mandatory
license = "LGPLv3"
issueTrackerURL = "https://github.com/Kerite/mc-UniversalLanguagePatch/issues" #optional
[[mods]]
modId = "universallanguagepatch" #mandatory
version = "${file.jarVersion}" #mandatory
displayName = "Universal Language Patch"
#updateJSONURL="http://myurl.me/" #optional
displayURL = "https://github.com/Kerite/mc-UniversalLanguagePatch" #optional
#logoFile="universallanguagepatch.png" #optional
#credits="" #optional
authors = "Keriteal" #optional
description = '''Patch text in Minecraft'''
[[dependencies.universallanguagepatch]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[36,)" #mandatory
ordering = "NONE"
side = "BOTH"
[[dependencies.universallanguagepatch]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,1.17)"
ordering = "NONE"
side = "BOTH"
